Usage of circular constraints in getByPath
clickbar/dot-diver pull request #11
Opened 2023-10-10 12:13 UTC by djfhe

Adds usage of circular constraints for the constraining type in getByPath.

Still WIP.

2024-03-27 21:13 UTC, djfhe commented
Still wip but pretty far.
Resolve https://github.com/clickbar/dot-diver/issues/5 by taking advantage of circular references using a tuple trick.

Still want to solve:
- https://github.com/clickbar/dot-diver/issues/3
- https://github.com/clickbar/dot-diver/issues/2
- https://github.com/clickbar/dot-diver/issues/4

before merging this into main.
This should be v2 then since we break backwards compatibility by changing the `Path` type and custom implementations.

Unsure if i can solve
https://github.com/clickbar/dot-diver/issues/1
but i don't think this will really be necessary anymore, since we now support nearly max depth while also showing a sane number of path (currently the next two levels).

2024-03-31 18:25 UTC, djfhe commented
i think i fixed
https://github.com/clickbar/dot-diver/issues/3
and
https://github.com/clickbar/dot-diver/issues/4

i still have to look a bit more into https://github.com/clickbar/dot-diver/issues/2.
Additional runtime checks are also required to check if the typescript behavior is the same as the javascript one.

I would like to also add some performance checks/tests to find potential regressions and/or problems.

2024-06-02 18:01 UTC, djfhe commented
@saibotk u can already take a look if you want.
But otherwise, it should be pretty much be ready.

2024-08-18 03:52 UTC, saibotk requested changes

2024-08-18 03:52 UTC, saibotk commented on src/index.ts
> +type IsTuple<T> = T extends readonly [any, ...any[]] ? true : false
maybe use unknown here too?

https://github.com/sindresorhus/type-fest/blob/2967fe62b55c7cc13fa003259e119f98edeb9c28/source/internal/array.d.ts#L13

2024-08-18 03:52 UTC, saibotk commented on src/index.ts
> +}
Maybe use https://github.com/sindresorhus/type-fest/blob/2967fe62b55c7cc13fa003259e119f98edeb9c28/source/writable-keys-of.d.ts#L28

2024-08-18 03:52 UTC, saibotk commented on src/index.ts
> +type BeforeLast<T extends string, V extends string | number> = T extends string
Add a comment and maybe rename this type

2024-08-18 03:52 UTC, saibotk commented on src/index.ts
> + * by the last parent in the given offset.
```suggestion
 * from the last parent at the given offset.
```

2024-08-18 03:52 UTC, saibotk commented on src/index.ts
> + * TODO: Find out why this works and if it may break in the future.
still relevant?

2024-08-18 03:52 UTC, saibotk commented on src/index.ts
> + * Path return all paths in the given type and returns them until it reaches its max depth.
```suggestion
 * Path returns all paths in the given type and returns them until it reaches its max depth.
```

2024-08-18 03:52 UTC, saibotk commented on src/index.ts
> +
can be removed

2024-08-18 03:52 UTC, saibotk commented on test/index.test-d.ts
> +it('Adds undefined if it is uncertain if the property exists', () => {
```suggestion
it('Adds undefined if it is uncertain if the property exists in a union', () => {
```

2024-08-18 03:52 UTC, saibotk commented on test/index.test-d.ts
> +it('Does not need to add undefined if it is certain that the property exists', () => {
```suggestion
it('Does not add undefined if it is certain that the property exists on unions', () => {
```

2024-08-18 03:52 UTC, saibotk commented on test/index.test-d.ts
> +test('Readonly config works with Path', () => {
```suggestion
test('Writable config works with Path', () => {
```

2024-08-18 03:56 UTC, saibotk requested changes

2024-08-18 03:56 UTC, saibotk commented on README.md
>  This is further explained in this [issue](https://github.com/clickbar/dot-diver/issues/1).
explain that this is only relative to the current offset.

2024-08-18 04:48 UTC, saibotk requested changes

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +## [2.0.0](https://github.com/clickbar/dot-diver/tree/2.0.0) (2024-03-25)
```suggestion
## [2.0.0](https://github.com/clickbar/dot-diver/tree/2.0.0) (2024-08-18)
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +## features
```suggestion
## Features
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +Support Paths up to a depth of 40 (limited by TypeScript's recursion depth) by cyclic constraints to only lookup up
```suggestion
Support paths up to a depth of 40 (limited by TypeScript's recursion depth) by utilizing cyclic constraints to only lookup up
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +the next 3 (default) levels. The limit of 40 comes by accessing the value at this depth level. This should
```suggestion
the next 3 (default) levels. This should
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +In general the `depth` limit of Path is no long the max depth, but instead a 'lookahead' depth. E.g. if you have a depth limit of 3,
```suggestion
In general the `depth` limit of `Path` is no longer the max depth, but instead a 'lookahead' depth. E.g. if you have a depth limit of 3,
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +constraint the max depth of the path, but only the lookahead depth. If this is a problem for you, please open a issue.
```suggestion
constrain the max depth of the path, but only the lookahead depth. If this is a problem for you, please open an issue.
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +In 1.0.0 you got the full type of nested unions.
```suggestion
In 1.0.0 you received the full type for nested unions.
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +This is incorrect behavior, as `a` could be a number and not an object with a `nested` property. This is now fixed.
```suggestion
This is incorrect behavior, because `a` could also be a number and not an object with a `nested` property. This is now fixed.
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +```PathValue``` got now splitted into two different types:
```suggestion
```PathValue``` was split into two different types:
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +these behave different when accessing values in a object.
```suggestion
the resulting types differ when accessing values in an object or setting them.
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +These type are used by there respective functions `getByPath` and `setByPath` and should more accurately represent the types of accessed values but can break old code.
```suggestion
These type are used by their respective functions `getByPath` and `setByPath` and should more accurately represent the types of accessed values but can potentially break old code.
```

2024-08-18 04:48 UTC, saibotk commented on CHANGELOG.md
> +If you implemented them to change the depth limit you might not need them anymore, as the (max) depth is now 40. (limited by access to the path value at that depth)
```suggestion
If you implemented them to change the depth limit you might not need them anymore, as the (max) depth is now 40 (limited by TypeScript's recursion limit).
```

2024-08-18 05:17 UTC, saibotk approved these changes
Let's shippppp

2024-08-18 05:21 UTC, merged