Add test case for empty path
clickbar/dot-diver pull request #31
Opened 2024-05-20 17:54 UTC by djfhe

Add some test cases to ensure correct handling of an empty path.

2024-05-26 12:54 UTC, saibotk requested changes

2024-05-26 12:54 UTC, saibotk commented on test/index.test.ts
> +  // @ts-expect-error - '' is not define on the property, so it is correct that typescript throws an error here
```suggestion
  // @ts-expect-error - '' is not defined on the object, so it is correct that typescript throws an error here
```

2024-05-26 12:54 UTC, saibotk commented on test/index.test.ts
> +  // @ts-expect-error - '' is not set on the property, so typescript should throw an error here
```suggestion
  // @ts-expect-error - '' is not set on the object, so typescript should throw an error here
```

2024-05-26 12:54 UTC, saibotk commented on test/index.test.ts
> +  setByPath(test, '', 'bar')
this and the one line afterwards should rather get their own test case. The test name only implies that the access to an unset path is tested

2024-05-26 12:54 UTC, saibotk commented on test/index.test.ts
> +it('it returns undefined when accessing an unset path', () => {
```suggestion
it('returns undefined when accessing an unset path', () => {
```

2024-06-02 18:03 UTC, djfhe commented
i would close this PR in favor of https://github.com/clickbar/dot-diver/pull/11. I don't see any use in merging this PR right before 2.0 where we change this behavior anyways. @saibotk

2024-06-02 19:17 UTC, closed without merging