Fix reactivity conflict caused by Object.prototype.hasOwnProperty
clickbar/dot-diver pull request #35
Opened 2024-08-15 09:02 UTC by Tofandel

Fixes #34

2024-08-15 09:16 UTC, saibotk approved these changes
Looks good to me thank you very much!

Can you fix the eslint warnings ans add some ignores for the hasOwnProperty usage with a comment that this is to allow reactivity?

Oh and quickly add a line to the Changelog and we are ready to merge

2024-08-15 09:25 UTC, Tofandel commented
Done

2024-08-18 02:02 UTC, djfhe requested changes
Hi, thanks for looking into this!
I suggest an alternative solution to avoid any security risks while still fixing it.

Let me here your thoughts on this!

2024-08-18 02:02 UTC, djfhe commented on src/index.ts
> +      !current?.hasOwnProperty(pathPart) // We use the builtin to avoid reactivity issues with Proxy
```suggestion
     current === null ||
      current[pathPart] === undefined || // Trigger dependency tracking for libraries (e.g. vue)
      !hasOwnProperty.call(current, pathPart)
```

I would suggest this. We still use the global `hasOwnProperty` function but signal vue, that we access the property so its depedency tracking works.

2024-08-18 02:02 UTC, djfhe commented on src/index.ts
> +      !current?.hasOwnProperty(pathPart)
```suggestion
     current === null ||
      current[pathPart] === undefined || // Trigger dependency tracking for libraries (e.g. vue)
      !hasOwnProperty.call(current, pathPart)
```

The same here. Adding this undefined check should not change behavior, since the check in line 292 would have catched the undefined `parentObject` otherwise.

2024-08-20 11:05 UTC, Tofandel commented on src/index.ts
> +      !current?.hasOwnProperty(pathPart)
This seems like a good alternative, I see that you already released it, so I will close this

2024-08-20 11:05 UTC, closed without merging